language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  # Boost
  - BOOST_VERSION=default
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libboost-all-dev
sudo: required
before_install:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
install:
  - pip install Cython
  - pip install .
# command to run tests
script:
  - nosetests