language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  # Boost
  - BOOST_VERSION=def
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libboost-all-dev
install:
  - pip install Cython
  - pip install .
# command to run tests
script:
  - nosetests