language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
  - os: linux
  - os: osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
before_install:
- |
  if ["$TRAVIS_OS_NAME" = "linux"]; then export CXX=g++-4.8 CC=gcc-4.8; fi
install:
  - pip install Cython
  - pip install .
# command to run tests
script:
  - nosetests