language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  # Boost
  - BOOST_VERSION=default CC=/usr/bin/gcc-5 CXX=/usr/bin/g++-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libboost-all-dev
sudo: false
install:
  - pip install Cython
  - pip install .
# command to run tests
script:
  - nosetests