language: python
cache: pip
python:
- '3.4'
- '3.5'
- '3.6'
env:
  global:
  - AWS_S3_REGION="us-east-1"
  - AWS_S3_BUCKET="elit-public"
  - secure: oYpsqiUOqYgJ7VxGbv+C6ExRCKWOPdoCKiEANffK+r2lcMCciEwNwXLKIenOSBChdPeqW6KPyfHuzjqmj7hM7GWSKczbNS5T5B/E60FAnijQv52+RvBMnS7OPjUaRwQwiXwDlev0DauhvwPKCC0KOTnjWRfT0VNjZ/BvkAWXGY+YCrgKRRBaTx3do6kFEeBkat4uxG2CjHH7pojUIDkZ9j6g2WCmoDUtCz/KTnWx3k9U/1DOW3x4rbq/JemJ3zBiV5juV7d/+/VhYsGexcuIUySRpRlG8OENVInlpXks9db3M366CKcf20E63eMPs8VsnMpGHYUUifwYnXrY0YoL5I3kfKMx4z0vHPpSqFBirU+Nwl8MLx7X14m+bxwsIgW6+xOAp6ptc68s+FQfTb/Vknu7kQ0IAAr7wu8W9iMENBNmRgXS75eHfPOFw+jk+rARbx97XRg6lAdW2o1QVu0L/yFYc4HiL288id9xa0LDjy0Hm1ShW8wv660bMkL5ApzP0Hns1nZNC7GfP3J3VbO6kUDp06VIT8In/IFxiOhI+1XVu9XDbsmHHBgnGJ7Iq/IUM8ViL8s0IUBmTcYKM5BFfLp0jg45EYFgAWWLY6B/TS0VpwDL+H2Ao7Enmj19cMflzS/TV8EAeuXh2KijFQMtjx6lyIHvQffhSnd6e9oNXjc=
before_install:
- pip install awscli
- export PATH=$PATH:$HOME/.local/bin
- aws s3 cp s3://elit-public/resources/tokenize /home/travis/build/elitcloud/resources/tokenize
  --recursive
install:
- pip install .
deploy:
  provider: pypi
  user: emorynlp
  password:
    secure: XTttyWsWYPYrsAoJ/cCQjg1kpW8KzO2jZ89rACtgFPB/dJZL4q1HsLeMUIKtecMX0QZJfOXob9Kj0dBYD9KoybRb5HhBcMFkKc1k1RfSpSZblbWwmAKvyyjLkK2FgNLfSqWom41geTlqRwaoCEO7PtD0mn98/KSvFbvHYELmqn1NscdtbTR4HWyP0elIPrMDFPMeX7GtWll7Bnjt1pI//0Mcv+4jB/lHPCvyh809OgPNKqA2vS97vQ7wJ/rBk+Qiu8a6taf7hYxHUxpwLkAEaGSQz92+OJzwmY6trQcJw5j9pMBfwGPSMz1r5TWd2g7VwmIGH/KM0U0WI0wPOJt9wnynYzfaa6633Ctzihmt2GLfQxcuhc427oHlKKHjmd5tCn8isjsLJICg8WeoWwcDLljsOunQfaaKDuZuchY2ol8gjmwvM9ATC4nZtGfFr0cPr3Et1GZcZcBG5LnNE8hzQDNGthHQuqmSH5gB2sdUfbU935MGL2xA/5SFOHz6C06uupv8tgjj2lQwaKxXNBX/5cEhoNe+4yaYcAFM3hN+BLyzW08xCg5SGgH1htJ5Nj+jC3SnlnIU6Y0DvENuEyuTpy6H5LdfhZW/VorwWsAfd7uQiT0UgveFMZ6pc/vnyqB9jTdReqgi3JHCBYVx/hlHvGhx35y7Gsr5PTG4kN9slT4=
  on:
    tags: true
    branch: master
script:
- pytest
notifications:
  email: false
